# 数据库配置
database:
  host: localhost
  port: 3306
  user: root
  password: lh123456
  dbname: gin_blog
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # 秒

# 服务器配置
server:
  port: 8080
  mode: release  # debug, release, test
  read_timeout: 10   # 秒
  write_timeout: 10  # 秒
  max_header_bytes: 1048576  # 1MB

# JWT配置
jwt:
  secret: gin_blog_jwt_secret_key_2025_a8b9c7d6e5f4g3h2i1j0k9l8m7n6o5p4
  expires_hours: 24

# 日志配置
log:
  level: info  # debug, info, warn, error
  format: json  # json, text
  output: stdout  # stdout, file
  file_path: logs/app.log