// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CommentInfo struct {
	Id        int64  `json:"id"`
	Content   string `json:"content"`
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	PostId    int64  `json:"post_id"`
	CreatedAt string `json:"created_at"`
}

type CommentListReq struct {
	PostId   int64 `form:"post_id"`
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"page_size,default=10"`
}

type CommentListResp struct {
	Total    int64         `json:"total"`
	Page     int64         `json:"page"`
	PageSize int64         `json:"page_size"`
	List     []CommentInfo `json:"list"`
}

type CreateCommentReq struct {
	PostId  int64  `json:"post_id"`
	Content string `json:"content"`
}

type CreatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"user_info"`
}

type PostInfo struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type PostListReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"page_size,default=10"`
}

type PostListResp struct {
	Total    int64      `json:"total"`
	Page     int64      `json:"page"`
	PageSize int64      `json:"page_size"`
	List     []PostInfo `json:"list"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UpdatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
}
